### ISSUE TITLE
bug: 偶发编译bug

### ISSUE THREAD

**Issue by chen610620** [umijs/mako#1605]
由于是公司内部项目， 且项目较大，无法提供太过具体的bug详情。 

项目基于前两年的antd design pro进行开发。 已升级到antd v5。
报错是在gitlab上进行cicd时报错(使用docker.fxxk.dedyn.io/node:lts 作为编译容器)。  
```Dockerfile
WORKDIR /app
COPY . .
RUN npm config set strict-ssl false && npm install --legacy-peer-deps --registry=https://registry.npmmirror.com
RUN NODE_ENV=production npm run build
```
编译报错： 
```log
#10 22.75 thread 'rayon thread 0' panicked at crates/mako/src/plugins/tree_shaking/shake/module_concatenate/concatenated_transformer.rs:125:63:
#10 22.75 called `Option::unwrap()` on a `None` value
#10 22.75 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
#10 23.79 Rayon: detected unexpected panic; aborting
#10 24.04 Aborted (core dumped)
#10 ERROR: process "/bin/sh -c NODE_ENV=production npm run build" did not complete successfully: exit code: 134
------
 > [build-stage 5/5] RUN NODE_ENV=production npm run build:
------
process "/bin/sh -c NODE_ENV=production npm run build" did not complete successfully: exit code: 134
```
![image](https://github.com/user-attachments/assets/311dd251-4546-4c91-a1b6-0e8828538914)

**Comment by chen610620** [comment]
项目为react项目。 前端tsx文件存在循环依赖情况。

**Comment by chen610620** [comment]
解决了所有的循环依赖。 但是还是会出现编译报错情况

**Comment by stormslowly** [comment]
1. mako 版本给下
2. 是否配置了 ignore，可以先配置关闭 concatnate 绕过下
项目根目新建 mako.config.json 内容如下
```json
{
  "optimization": {
    "skipModules": true,
    "concatenateModules": true
  }
}
```

**Comment by chen610620** [comment]
补充mako版本信息：

**Comment by chen610620** [comment]
当前最新编译报错：
```log
#7 [build-stage 4/5] RUN npm config set strict-ssl false && npm install --legacy-peer-deps --registry=https://registry.npmmirror.com/
#7 sha256:b45c1cf1274efba08b00d87c1b914c40c27f4c36[57](https://gitlab.jhlfund.com/eam/bd/eqw/react-web/-/jobs/31113#L57)b963657b3153038aeb6b35
#7 149.7 
#7 149.7 > quantweb@2.3.5 postinstall
#7 149.7 > max setup
#7 149.7 
#7 151.5 😄 Hello PRO
#7 151.5 info  - [你知道吗？] COMPRESS=none max build 可以关闭项目构建时的代码压缩功能, 方便调试项目的构建产物。
#7 151.5 info  - [plugin: ./node_modules/@umijs/preset-umi/dist/features/mako/mako] Using mako@0.8.11
#7 151.5 info  - [plugin: ./node_modules/@umijs/preset-umi/dist/features/mako/mako] Mako is an extremely fast, production-grade web bundler based on Rust. If you encounter any issues, please checkout https://makojs.dev/ to join the community and report the issue.
#7 151.5 info  - generate files
#7 153.0 info  - Preparing...
#7 154.4 info  - [icons] generate icons local:notebook-pen, local:book
#7 155.4 
#7 155.4 added 4 packages in 3m
#7 155.4 
#7 155.4 [59](https://gitlab.jhlfund.com/eam/bd/eqw/react-web/-/jobs/31113#L59)0 packages are looking for funding
#7 155.4   run `npm fund` for details
#7 DONE 155.5s
#6 [build-stage 5/5] RUN NODE_ENV=production npm run build
#6 sha256:b9b028c6e9790423a1d71f6c2c3889027a2f9d9a1983965fc66c26ed8fc53f6c
#6 0.390 
#6 0.390 > quantweb@2.3.5 build
#6 0.390 > max build
#6 0.390 
#6 1.817 😄 Hello PRO
#6 1.817 info  - [你知道吗？] 想快速修改 html 模板、DIY 项目？试试编写项目级插件，详见 https://umijs.org/docs/guides/directory-structure#plugints
#6 1.819 info  - [plugin: ./node_modules/@umijs/preset-umi/dist/features/mako/mako] Using mako@0.8.11
#6 1.819 info  - [plugin: ./node_modules/@umijs/preset-umi/dist/features/mako/mako] Mako is an extremely fast, production-grade web bundler based on Rust. If you encounter any issues, please checkout https://makojs.dev/ to join the community and report the issue.
#6 1.820 info  - Umi v4.3.20
#6 3.289 info  - Preparing...
#6 4.763 info  - [icons] generate icons local:notebook-pen, local:book
#6 5.740 
#6 5.740 Rebuilding...
#6 7.[60](https://gitlab.jhlfund.com/eam/bd/eqw/react-web/-/jobs/31113#L60)7 
#6 7.607 Done in 1879ms.
#6 7.[62](https://gitlab.jhlfund.com/eam/bd/eqw/react-web/-/jobs/31113#L62)2 info  - [plugin: ./node_modules/@umijs/plugins/dist/tailwindcss] tailwindcss service exited
#6 7.[63](https://gitlab.jhlfund.com/eam/bd/eqw/react-web/-/jobs/31113#L63)3 
#6 7.633 =====================================================================================================
#6 7.633 
#6 7.633    █████   ███   █████   █████████   ███████████   ██████   █████ █████ ██████   █████   █████████
#6 7.633   ░░███   ░███  ░░███   ███░░░░░███ ░░███░░░░░███ ░░██████ ░░███ ░░███ ░░██████ ░░███   ███░░░░░███
#6 7.633    ░███   ░███   ░███  ░███    ░███  ░███    ░███  ░███░███ ░███  ░███  ░███░███ ░███  ███     ░░░
#6 7.633    ░███   ░███   ░███  ░███████████  ░██████████   ░███░░███░███  ░███  ░███░░███░███ ░███
#6 7.633    ░░███  █████  ███   ░███░░░░░███  ░███░░░░░███  ░███ ░░██████  ░███  ░███ ░░██████ ░███    █████
#6 7.633     ░░░█████░█████░    ░███    ░███  ░███    ░███  ░███  ░░█████  ░███  ░███  ░░█████ ░░███  ░░███
#6 7.633       ░░███ ░░███      █████   █████ █████   █████ █████  ░░█████ █████ █████  ░░█████ ░░█████████
#6 7.633        ░░░   ░░░      ░░░░░   ░░░░░ ░░░░░   ░░░░░ ░░░░░    ░░░░░ ░░░░░ ░░░░░    ░░░░░   ░░░░░░░░░
#6 7.633 
#6 7.633 
#6 7.633   Mako bundler does not support the following options:
#6 7.633     - chainWebpack
#6 7.633 
#6 7.633   So this project may fail in compile-time or error in runtime, please test and release carefully.
#6 7.633 =====================================================================================================
#6 7.633       
#6 7.907 Building with mako for production...
#6 24.28 thread 'rayon thread 0' panicked at crates/mako/src/plugins/tree_shaking/shake/module_concatenate/concatenated_transformer.rs:125:63:
#6 24.28 called `Option::unwrap()` on a `None` value
#6 24.28 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
#6 25.24 Rayon: detected unexpected panic; aborting
#6 25.47 Aborted (core dumped)
#6 ERROR: process "/bin/sh -c NODE_ENV=production npm run build" did not complete successfully: exit code: 134
------
 > [build-stage 5/5] RUN NODE_ENV=production npm run build:
------
process "/bin/sh -c NODE_ENV=production npm run build" did not complete successfully: exit code: 134
ERROR: Job failed: exit code 1
```
补充编译日志(未添加 mako.config.json  文件情况下报错信息)

**Comment by chen610620** [comment]
添加mako.config.json 配置后，编译正常

**Comment by stormslowly** [comment]
@Jinbao1001 maybe related to https://github.com/umijs/mako/pull/1584

**Comment by Jinbao1001** [comment]
let me cc
