### ISSUE TITLE
Less 文件中使用 @import '/src/global.less' 会出现错误

### ISSUE THREAD

**Issue by tangbzai** [umijs/mako#1666]
## 问题描述
在 less 文件中使用`@import '/src/global.less'`会出现错误。

**目前尝试后了解的情况**
1. 改为`@import '@/global.less'`则不会报错（但是vscode中无法通过ctrl+左键的方式跳转到对应的文件）
2. 使用`webpack`（注释掉`mako: {}`）时是没问题的
## 错误内容
```
Uncaught Error: Module build failed:
Tsfn promise rejected GenericFailure, Error: FileError: Less resolver error:
'/src/global.less' wasn't found. Tried - /src/global.less

Enhanced resolver error details:
resolve '/src/global.less' in '/githubProject/mako-umi-plugin/src/pages'
  using description file: /githubProject/mako-umi-plugin/package.json (relative path: ./src/pages)
    No description file found in /src or above
    no extension
      /src/global.less doesn't exist
    .less
      /src/global.less.less doesn't exist
    .css
      /src/global.less.css doesn't exist
    as directory
      /src/global.less doesn't exist

Enhanced resolver error missing:
undefined

 in /githubProject/mako-umi-plugin/src/pages/index.less on line 1, column 1:
1 @import '/src/global.less';
2 
.
    at src/pages/index.less?asmodule (G:\githubProject\mako-umi-plugin\src\pages\index.less:1:7)
    at requireModule (umi.ts:79:7)
    at fn (umi.ts:79:7)
    at src/pages/index.tsx (index.tsx:1:20)
    at requireModule (umi.ts:79:7)
    at Function.fn (umi.ts:79:7)
    at umi.ts:79:7
```
![image](https://github.com/user-attachments/assets/0e3287d8-486e-444b-bf14-c26f17fbfc60)
## 复现仓库
[复现仓库](https://github.com/tangbzai/mako-less-import-repeat-demo)
## 期望效果
期望可兼容`@import '/src/global.less'`的方式

**Comment by stormslowly** [comment]
建议还是改成 歧义更小的相对路径的方式
