### ISSUE TITLE
Windows build 出现 not found in the module graph

### ISSUE THREAD

**Issue by tangbzai** [umijs/mako#1668]
## 复现步骤
1. 使用 umi 创建项目，配置 `mako: {}`
2. 运行 build 命令（*注意，dev命令不会出现错误）

## 环境信息
umi: 4.3.28
nodejs: 20.12.2
windows: 10 22H2

## 错误信息
```
info  - [plugin: ./node_modules/.pnpm/@umijs+preset-umi@4.3.28_@types+node@22.8.2_@types+react@18.3.12_lightningcss@1.27.0_rollup@4_m7i5wnit2cgn7ajzlxzgjvihy4/node_modules/@umijs/preset-umi/dist/features/mako/mako] Using mako@0.9.3
info  - [plugin: ./node_modules/.pnpm/@umijs+preset-umi@4.3.28_@types+node@22.8.2_@types+react@18.3.12_lightningcss@1.27.0_rollut@18.3.12_lightningcss@1.27.0_rollup@4_m7i5wnit2cgn7ajzlxzgjvihy4/node_modules/@umijs/preset-mako@0.9.3umi/dist/features/mako/mako] Mako is an extremely fast, production-grade web bundler based ont@18.3.12_lightningcss@1.27.0_rollu Rust. If you encounter any issues, please checkout https://makojs.dev/ to join the communitys an extremely fast, production-gra and report the issue.                                                                       / to join the community and report 
info  - Umi v4.3.28
info  - Preparing...
Building with mako for production...
● Mako ▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨ (65%) generate begin generate begin
                                   thread 'Mako thread 1' panicked at crates\mako\src\module_graph.rs:192:32:
module_id ModuleId { id: "D:/project\\mako-umi-demo\\node_modules\\.pnpm\\history@5.3.0\\node_modules\\history\\index.js.0\\node_modules\\history\\index.js" } not found in the module graph
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Rayon: detected unexpected panic; aborting
 ELIFECYCLE  Command failed with exit code 3221226505.
```

**Comment by fakerqu** [comment]
● Mako ▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨ (62%) generate begin generate begin                                                                                                                                    thread 'Mako thread 1' panicked at crates\mako\src\module_graph.rs:192:32:
module_id ModuleId { id: "D:/*******\\*******\\node_modules\\.pnpm\\rc-util@5.43.0_react-dom@18.3.1_react@18.3.1__react@18.3.1\\node_modules\\rc-util\\es\\Dom\\styleChecker.js" } not found in the module graph
stack backtrace:
   0:     0x7ff8d70726ad - napi_register_module_v1
   1:     0x7ff8d70912a9 - napi_register_module_v1
   2:     0x7ff8d706d111 - napi_register_module_v1
   3:     0x7ff8d7074547 - napi_register_module_v1
   4:     0x7ff8d7074139 - napi_register_module_v1
   5:     0x7ff8d7074c82 - napi_register_module_v1
   6:     0x7ff8d7074ac6 - napi_register_module_v1
   7:     0x7ff8d707301f - napi_register_module_v1
   8:     0x7ff8d70746a6 - napi_register_module_v1
   9:     0x7ff8d8df2f64 - napi_register_module_v1
  10:     0x7ff8d6e9f414 - napi_register_module_v1
  11:     0x7ff8d6f2cf9a - napi_register_module_v1
  12:     0x7ff8d6ea0c3b - napi_register_module_v1
  13:     0x7ff8d733396c - napi_register_module_v1
  14:     0x7ff8d7346e0f - napi_register_module_v1
  15:     0x7ff8d6e95123 - napi_register_module_v1
  16:     0x7ff8d70ad78b - napi_register_module_v1
  17:     0x7ff8d70aeb23 - napi_register_module_v1
  18:     0x7ff8d6e6f8dc - napi_register_module_v1
  19:     0x7ff8d6d47941 - <unknown>
  20:     0x7ff8d8df0f42 - napi_register_module_v1
  21:     0x7ff8d7059847 - napi_register_module_v1
  22:     0x7ff8d7b49df2 - napi_register_module_v1
  23:     0x7ff8d7b4bdce - napi_register_module_v1
  24:     0x7ff8d708214d - napi_register_module_v1
  25:     0x7ff946eddbe7 - BaseThreadInitThunk
  26:     0x7ff947e05a6c - RtlUserThreadStart
● Mako ▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨ (65%) generate begin generate begin                                                                                                                                    Rayon: detected unexpected panic; aborting
 ELIFECYCLE  Command failed with exit code 3221226505.

**Comment by fakerqu** [comment]
使用pnpm run dev无问题，使用npm run build也无问题，只有使用pnpm run build会异常

**Comment by phoema** [comment]
关注
